; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.4 on Thu Oct 21 2021 12:40:04 GMT-0400 (Eastern Daylight Time)

G28 ; home
;M401 ; extending BLTouch Probe
G30 P0 X2000 Y100 Z-9999
G30 P1 X90 Y100 Z-9999
G30 P2 X90 Y960 Z-9999
G30 P3 X2000 Y960 Z-9999 S4
;M402 ; Retracting BLTouch Probe
