; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Sat May 13 2023 11:36:34 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


