; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.4 on Thu Oct 21 2021 12:40:04 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


