; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Tue Jan 25 2022 16:04:08 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

