; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Sat May 13 2023 11:36:36 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

